# netlify.toml

[build]
  # Thư mục chứa các file build cuối cùng của dự án frontend của bạn.
  # Thay đổi 'build', 'dist', 'public' hoặc tên thư mục output của dự án bạn.
  publish = "dist"

  # Lệnh build dự án của bạn.
  # Thay đổi 'npm run build', 'yarn build' hoặc lệnh build tương ứng của dự án bạn.
  command = "npm run build"

[[redirects]]
  # Quy tắc chuyển hướng này đảm bảo rằng tất cả các đường dẫn không tìm thấy file
  # sẽ được chuyển hướng về index.html. Điều này rất quan trọng cho các ứng dụng
  # Single Page Application (SPA) sử dụng client-side routing.
  from = "/*"
  to = "/index.html"
  status = 200

# Các phần tùy chọn khác bạn có thể thêm vào:

# [context.production]
# Các cài đặt đặc biệt chỉ áp dụng cho môi trường production (sau khi deploy chính thức).
# Ví dụ:
# environment = { API_URL = "https://api.yourgame.com/prod" }

# [context.deploy-preview]
# Các cài đặt đặc biệt cho các bản deploy preview (khi bạn tạo PR trên GitHub/GitLab).
# Ví dụ:
# environment = { API_URL = "https://api.yourgame.com/dev" }

# [dev]
# Cài đặt cho môi trường phát triển cục bộ khi dùng 'netlify dev'.
# command = "npm start"  # Lệnh để khởi chạy dev server của bạn (ví dụ: React App)
# port = 3000            # Cổng mà dev server của bạn đang chạy
# publish = "public"     # Thư mục local mà dev server sẽ phục vụ