import { Item, ItemType } from '../types';

// This file defines blueprints for special items that can be created in the game.
// The actual items in inventory will have a unique `id` generated by uuidv4.

export const ITEM_BLUEPRINTS: { [key: string]: Omit<Item, 'id'> } = {
    BACH_CO_DAN: {
        name: 'Bách Cơ Đan',
        description: 'Một viên đan dược huyền diệu. Sử dụng sẽ ngẫu nhiên tăng 1 điểm cho một trong bốn loại kỹ năng cơ bản.',
        type: ItemType.ĐanDược,
        onUseEffect: {
            type: 'RANDOM_SKILL_BOOST',
            value: 1,
        }
    }
};
